### ISSUE TITLE
Add functionality so that drift chamber planes can be shifted 

### ISSUE THREAD

**Issue by hszumila** [JeffersonLab/hcana#237]
Currently the only x and y positions for the drift chambers are global for full chamber. Each plane in a drift chamber should be able to shifted in x and y position for optimizing the alignment.

**Comment by sawjlab** [comment]
This has been done in the past by adjusting the values of Xdc_central_wire which are per plane.  But there is something to be said for keeping the central wire values at their nominal design values and doing small offsets some other way.

**Comment by MarkKJones** [comment]
Holly submitted pull request with changed code that was accepted.

https://github.com/JeffersonLab/hcana/commit/d4a1953f70bd179981d23fdd221e443d907acc37
