### ISSUE TITLE
MYDIR remains undefined if called from a shell script

### ISSUE THREAD

**Issue by vargasa** [JeffersonLab/hcana#248]
$MYDIR is not being defined if "source setup.csh" is called from a script (in interactive mode there is no problem).

You can reproduce the issue by running a shell script such a:

```
#!/bin/csh -vx
# _FILE_ SetHcana.csh
set HCANADIR="/path/to/hcana/"
source "$HCANADIR/setup.csh"
hcana -l -b -q SomeScript.C
```
Then, 

`./SetHcana.csh
`

Which will display:

```
/path/to/hcana/: error while loading shared
libraries: libHallC.so: cannot open shared object file: No such file or
directory.
```

**Comment by hansenjo** [comment]
Which platform are you on? On Mac, SIP prevents resetting DYLD_LIBRARY_PATH in a script.

**Comment by vargasa** [comment]
I'm using Ifarm, CentOS Linux release 7.2.1511 (Core)

**Comment by sawatzky** [comment]
The underlying problem in the setup.csh script is that $_ is assumed to contain the path to the sourced file, but that isn't true for any version of tcsh I've tried...  (I guess it must have worked for some version of tcsh?)  Anyway, that fails and ```$1``` is also empty in the else clause so the script fails.

Perhaps that first code block should just be replaced with something like this?
```
diff --git a/setup.csh b/setup.csh
index 6713b3d..9637946 100644
--- a/setup.csh
+++ b/setup.csh
@@ -1,14 +1,14 @@
 #!/bin/csh

-set called=($_)
-if ("$called" != "") then
-  set scriptdir=$called[2]
-  set MYDIR=`dirname $scriptdir`
-  set MYDIR=`c\d $MYDIR && pwd`    # ensure absolute path
+if ( "$1" == "" ) then
+  echo "ERROR:  'setup.csh' must have a path to the script location as its argument"
+  echo "   ie. 'source /my/path/to/setup.csh /my/path/to/setup.csh'"
+  echo "   ie. 'source setup.csh `pwd`"
+  exit 1
 else
-  set scriptdir=$1
-  set MYDIR=$scriptdir
+  set MYDIR=$1
 endif
+
 setenv ANALYZER $MYDIR/podd
 setenv HCANALYZER $MYDIR
 # Check if LD_LIBRARY_PATH is defined
```

**Comment by hansenjo** [comment]
If I remember right, finding out the path to a script from within the
script is notoriously difficult/impossible in (t)csh. Check ROOT's
"thisroot.csh" for the community's current best attempt on this ...
