### ISSUE TITLE
Add config event handler for "TI setup data"

### ISSUE THREAD

**Issue by sawatzky** [JeffersonLab/hcana#271]
There is a (semi-)new TI config related blob in Event 125 that stores some trigger/TM related settings that needs a decoder in THcConfigEvtHandler.cxx.  Runs after SHMS 1295 and HMS 718 will have blobs with the information below.

The word format is defined by this code in the hcvme0[12].c ROLs:
```
/* Log prescales, misc TI related information from ffile */
*rol->dabufp++ = (0xd0000000);        // 'misc' header block
*rol->dabufp++ = (0xabcd0000+1);      // last +N is version ID number
*rol->dabufp++ = nped;                //
*rol->dabufp++ = scaler_period;       //
*rol->dabufp++ = syncCnt;             //
for(i=0; i<NUM_PRESCALES; i++) {      // Input Trigger prescale settings
  *rol->dabufp++ = prescales[i];
}
*rol->dabufp++ = (0xd000000f);        // 'misc' trailer block
```

**Comment by sawjlab** [comment]
Should I assume that NUM_PRESCALES is 6 or deduce it from the number of words between 0xd0000000 and 0xd000000f?

**Comment by sawjlab** [comment]
THcConfigEvtHandler now interprets this TI configuration data and as of commit 7d601556c39ce8128733d01d7d88bd29bf7ea9fc makes that data available in gHcParms.
