### ISSUE TITLE
Bug fix for THelicity

### ISSUE THREAD

**Issue by whit2333** [JeffersonLab/hcana#451]
@sawjlab Here is a little bug fix. Our fork is a little too far from this repo to submit a PR.

https://eicweb.phy.anl.gov/jlab/hallc/analyzer_software/hcana/commit/55998149395525b5bc0fecdfb19101d075da44cb

Cheers,
Whit

**Comment by sawjlab** [comment]
Was fixed a while ago.  The two variables are initialized in the constructor.
