### ISSUE TITLE
Warning Message of variable definition in THcDC.cxx 

### ISSUE THREAD

**Issue by Yero1990** [JeffersonLab/hcana#478]
While preparing a replay script for upcoming experiment, I found a warning message from HCANA concerning the definition of the variable "H.dc.track_hitpos", stating it had not being defined, apparently due to a potential typo in the definition.
--------------
Warning in <THaVarList::DefineVariables [called from THcDC("H.dc")::DefineVarsFromList]>: Too many dots in definition of variable H.dc.track_hitpos (Position of each hit in track). Variable not defined.
--------------

**Comment by MarkKJones** [comment]
I removed the tree variable for THcDC::DefineVariables since it was not being used.
I found another way to get the hit position info for the track to use in diagnostics.
