### ISSUE TITLE
hcana error

### ISSUE THREAD

**Issue by Yero1990** [JeffersonLab/hcana#485]
When I switch to hcana "develop" branch and replayed data, I got a seg. fault error (see attached)
However, when I revert back to hcana "firmware_update" branch, the data replay works fine.
I don't know if it may have to do with my own version, or has anyone also observed this issue?
![hcana_err](https://user-images.githubusercontent.com/16841706/185190572-80d531f5-7c3a-4415-9a33-ad751b694f12.png)

**Comment by MarkKJones** [comment]
Did you update PODD? The develop branch is using a different version of PODD.

**Comment by Yero1990** [comment]
Yes. I did:

git submodule init
git submodule sync
git submodule update

and then:

scons -j10

I will try it again, just to make sure.

**Comment by hansenjo** [comment]
Hmmm. The best way to track this down would be to run hcana in the 
debugger. Do you have the replay setup (script, database, raw data file) 
somewhere?

Ole

**Comment by Yero1990** [comment]
Yes, the replay is set-up in the Hall C Counting Room cdaq machines.

For example:

# Assuming you are on a desktop [hcdesk] machine in the Counting
House, open a terminal and login to cdaq
$ ssh cdaql1
#source a working version of ROOT cern (unfortunately this is done
each time a new session is started)
$ source /apps/root/6.22.08/setroot_CUE.csh
#change to the official cafe directory
$ cd cafe-2022/cafe_online_replay

Then run:
./hcana SCRIPTS/COIN/PRODUCTION/replay_cafe.C

I would have to revert back to the hcana "develop" branch before you try
the debugger, so you can reproduce the error.
Let me know.

**Comment by hansenjo** [comment]
Sorry for the delay. I'll have time to look at this by the end of the week.

**Comment by Yero1990** [comment]
Ok no problem Ole, thanks.

If you will be working on hcana on a cdaq machine, you can just copy
my version of the repo to your workspace:

My repo is located at: /home/cdaq/cafe-2022/hcana
I'm currently using the "firmware_update" branch, recall
the issue I had was with the "develop" branch

**Comment by MarkKJones** [comment]
I looked a bit into this. The TIBlobModule Init function was not being called. Not sure why this has changed
though in header it has "using PipeliningModule::Init;"

I force it to call Init in the LoadSlot . This fixed the error but now there is an warning in THcHitList.cxx when it compares the FADC modules trigger time to the TI trigger time.

**Comment by hansenjo** [comment]
I suppose the TIBlobModule is default-constructed somewhere, and it was forgotten to set fNumChan in the default constructor. Let me verify.

**Comment by MarkKJones** [comment]
I am confused about how TIBlobModule is initialized. As far as I can see the Init is called in the contructor.
We do not have it called in our scripts. We are mainly using it
to get the TI trigger time to compare to the individual FADC trigger times in the crate. Is there a better way?

**Comment by sawjlab** [comment]
TIBlobModule is a Decoder class.  So it should get constructed just like all the other Decoder classes as long as each TI is listed in db_cratemap.dat.

**Comment by hansenjo** [comment]
Init() is called from the regular constructor, but not the default constructor, which may be the problem, but I'm not sure yet. (The statement `using PipeliningModule::Init` is not a problem.) I guess it's ok to have a dedicated module for extracting trigger times. At least I can't think of a superior solution off the top of my head.

The TIBlobModule is not very well written though; I'll send some fixes soon that will make it more resilient to crashes. I do want to verify Carlos's report first. I need to copy his replay over to my home machine, so give me a little while.

**Comment by hansenjo** [comment]
@sawjlab Right. All the decoder modules are instantiated in THaSlotData::loadModule(), specifically line 144, which calls TClass::New(), which calls the default constructor. The module is then configured later in that routine through calls to SetSlot() and SetBank(). Apply this sequence to TIBlobModule, and one ends up with fNumChan = 0 (set in the Module::Module() default constructor). And TIBlobModule::LoadSlot makes the hardcoded assumption that fNumChan = 3. Crash.

I don't know for sure yet why this worked before, but I did streamline the decoder not too long ago, removing redundant calls to things like Init() and Clear(), exposing a logic flaw in TIBlobModule. Easy to fix.

**Comment by hansenjo** [comment]
I got to the bottom of the reason for the crash. It came down to a typo in Podd's PipeliningModule::Init function. I pushed a fix up to Podd's Release-170_patches branch. And I have a few more touchups for hcana, which I'll turn into a PR soon.

Meanwhile, I am puzzled as to the now-copious warnings about trigger time differences ("Big ADC Trigger Time Shift"). Investigating ...

**Comment by hansenjo** [comment]
Good news: Problem found. There was another typo, this time in TIBlobModule (forgot to rename a variable in commit 5183dbd2). All seems fine now. Preparing PR.

**Comment by hansenjo** [comment]
Resolved with commit 8a11eb22
