### ISSUE TITLE
Add per block adctdcoffset for NPS calorimeter

### ISSUE THREAD

**Issue by sanghwapark** [JeffersonLab/hcana#497]
Currently it has a global offset parameter (fAdcTdcOffset).
Need to:
- Replace it with array of per-block offset values to align the pulses
- Update the calibration parameter file with initial parameters set to 0.
- Test replay (with the offset parameters set to 0, we shouldn't see any difference)
- Test replay with some nonzero offset values

**Comment by MarkKJones** [comment]
I would suggest making the parameter array optional and set to zero by default

**Comment by sanghwapark** [comment]
#498 Closed.
