### ISSUE TITLE
Compilation error on Mac OS X for new addition of THcHodoHit.cxx

### ISSUE THREAD

**Issue by brash99** [JeffersonLab/hcana#99]
When compiling on Mac OS X Yosemite, I get the following error:

g++ -o src/THcHodoHit.os -c -O -Wall -Woverloaded-virtual -pthread -pthread -m64 -stdlib=libc++ -fPIC -fPIC -DNDEBUG -DMACVERS -DHAS_SSTREAM -DHALLC_MODS -I/Users/brash/Dropbox/Research/analyzer-evio/evio-4.4.5/Darwin-x86_64/include -Isrc -Ipodd/src -Ipodd/hana_decode -Ipodd/hana_scaler -I/Users/brash/Dropbox/root/include src/THcHodoHit.cxx
src/THcHodoHit.cxx:18:40: error: addition of default argument on redeclaration makes this constructor a default constructor
THcHodoHit::THcHodoHit( THcRawHodoHit *hit=NULL, Double_t posPed=0.0, 
                                       ^   ~~~~
src/THcHodoHit.h:19:3: note: previous declaration is here
  THcHodoHit( THcRawHodoHit* hit, Double_t posPed, 
  ^
1 error generated.
scons: *** [src/THcHodoHit.os] Error 1
scons: building terminated because of errors.

If I simply remove the "=NULL" definition on *hit, it compiles without issue.  I am just not sure how important this might be ... comments?

Best,
E.

**Comment by hansenjo** [comment]
If that constructor needs default arguments, they should be given in the
header file and not be repeated in the implementation. It looks like the
code has it the other way round.

Also, if there is a default constructor already, a constructor with only
default arguments will override it. This looks like a confused design.

Ole

**Comment by brash99** [comment]
OK, I moved the default argument declarations to the header file, and took them out of the implementation.  Pull request made ...

P.S.  This is not my code ... I hope I am not breaking something.

**Comment by sawjlab** [comment]
Assuming this issue can be closed.
